//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: MyBook.proto
namespace MyBook
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MyClass")]
  public partial class MyClass : global::ProtoBuf.IExtensible
  {
    public MyClass() {}
    
    private string _grade;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"grade", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string grade
    {
      get { return _grade; }
      set { _grade = value; }
    }
    private readonly global::System.Collections.Generic.List<MyBook.Person> _PersonList = new global::System.Collections.Generic.List<MyBook.Person>();
    [global::ProtoBuf.ProtoMember(2, Name=@"PersonList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MyBook.Person> PersonList
    {
      get { return _PersonList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Person")]
  public partial class Person : global::ProtoBuf.IExtensible
  {
    public Person() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private bool _sex;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
    private uint _age = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"age", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint age
    {
      get { return _age; }
      set { _age = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}